include:
  - project: 'univention/documentation/sphinx-docker'
    file: 'pipeline/sphinx.yml'

stages:
  - build
  - merge
  - production

.sphinx-doc:
  stage: build
  image: $SPHINX_BASE
  variables:
    DOC_TARGET_VERSION: "5.0"
    CHANGELOG_TARGET_VERSION: "5.0v6"
    language: "de"

.sphinx-html:
  extends:
    - .sphinx-html-template
    - .sphinx-doc

.sphinx-pdf:
  extends:
    - .sphinx-doc
    - .sphinx-pdf-template

.sphinx-linkcheck:
  extends:
    - .sphinx-doc
    - .sphinx-linkcheck-template

.sphinx-spelling:
  extends:
    - .sphinx-doc
    - .sphinx-spelling-template
