default:
  artifacts:
    expire_in: 1 day
  interruptible: true
  retry:
    max: 2
    when:
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  SPHINX_DOC: docker-registry.knut.univention.de/sphinx
  IMAGE_TAG: $CI_REGISTRY_IMAGE
  DOC: docker-registry.knut.univention.de/docbook
