default:
  artifacts:
    expire_in: 1 day
  interruptible: true
  retry:
    max: 2
    when:
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  CI_REGISTRY: docker-registry.knut.univention.de
  SPHINX_FULL: $CI_REGISTRY/sphinx
  SPHINX_BASE: $CI_REGISTRY/knut/sphinx-base
  GIT_SYNC: $CI_REGISTRY/knut/git-sync
  IMAGE_TAG: $CI_REGISTRY_IMAGE
  DOC: $CI_REGISTRY/docbook

