stages:
  - prepare
  - lint
  - build
  - test

variables:
  IMAGE_UCS_EC2_TOOLS: "gitregistry.knut.univention.de/univention/dist/ucs-ec2-tools:latest"

include:
  - project: univention/dist/docker-services
    file:
      - pre-commit.yml
  - project: univention/internal/ucsschool-ci-utils
    file: fragments/openstack.yaml
  - local: .gitlab-ci/docs.yml
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /skip-doc/ || $RUN_DOCS == "no"
        when: never
      - changes:
          paths:
            - "doc/ucsschool-import/**/*"
            - "doc/ucsschool-manual/**/*"
            - "doc/ucsschool-quickstart/**/*"
            - "doc/ucsschool-scenarios/**/*"
            - "doc/ucsschool-umc-user-import/**/*"
            - "doc/ucsschool-changelog/**/*"
        when: always

run pre-commit:
  stage: lint
  extends: .pre-commit

integration_tests:
  extends: .run_openstack_cfg
  stage: test
  needs: []
  rules:
    - changes:
        paths:
          - "*/**/debian/changelog"
      when: manual
      allow_failure: False
  variables:
    TARGET_VERSION: "5.0-9"
    OPENSTACK_CFG_FILE: ".gitlab-ci/branch_tests.cfg"
  script:
    - mkdir results
    - git fetch --depth 1 origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:compare
    - export PACKAGES_TO_INSTALL=$(git diff --name-only $CI_COMMIT_BRANCH compare | grep debian/changelog | sed 's/\(.*\)\/debian\/changelog/\1/g' | tr '\n' ' ')
    - !reference [.run_openstack_cfg, script]
    - .gitlab-ci/parse_junit.py
  artifacts:
    reports:
      junit: results/**/test-reports/**/*.xml
